### ISSUE TITLE
Files and images (Uploads) as part of the repository

### ISSUE THREAD

**Issue by vokimon** [Git-Mediawiki/Git-Mediawiki#21]
I don't know how hard would be to implement that, but it would be nice having the attachments (uploads, images) as part of the repository. So that you can add and edit images in local as you edit wiki pages.

**Comment by azrdev** [comment]
I added this in https://github.com/Git-Mediawiki/Git-Mediawiki/wiki/User-manual/fc5e6b1151c8e6439e8d42d192d3cf30571b957e -- feel free to correct/extend!

**Comment by moy** [comment]
Thanks. If anyone wants to see the diff, this link shows it directly: https://github.com/Git-Mediawiki/Git-Mediawiki/wiki/User-manual/_compare/3ac3163b64e1853c6bc123a3e4849bcae3d255f4...fc5e6b1151c8e6439e8d42d192d3cf30571b957e

I guess we're all set then.
