### ISSUE TITLE
All revisions imported twice

### ISSUE THREAD

**Issue by greenrd** [Git-Mediawiki/Git-Mediawiki#29]
I have tried twice now to do a

```
git clone -c remote.origin.pages=blah ...
```

and all of the revisions are imported twice. In the git log, all the changes happen, then all the changes happen again.

**Comment by moy** [comment]
Is this a public wiki? If not, can you reproduce on a public wiki?

**Comment by greenrd** [comment]
Yes, it's a public wiki - RationalWiki. I think the command was something like this:

    git clone -c remote.origin.pages=Existential_risk mediawiki:://http://rationalwiki.org/w/

**Comment by moy** [comment]
Weird indeed. Not sure I'll get time to investigate soon.

**Comment by simon04** [comment]
I can confirm this behaviour/bug for en.wikipedia.org for a page containing 21 revisions only

```
git clone -c remote.origin.pages=Webpack mediawiki::https://en.wikipedia.org/w
```

Tested using git 2.16.1 on Arch Linux.
