### ISSUE TITLE
user agent identification

### ISSUE THREAD

**Issue by chrysn** [Git-Mediawiki/Git-Mediawiki#31]
when requesting files from the mediawiki api, git-mediawiki sends the perl mediawiki library's default user agent (eg. "MediaWiki::API/0.41").

i suggest that a combined identifier be formed (eg. "git-mediawiki/2.6.2 MediaWiki::API/0.41") to make both the mediawiki api version and git-mediawiki with its version visible; this allows site administrators to easily find causes of performance issues. furthermore, it is [prescribed in the mediawiki api description](https://www.mediawiki.org/wiki/API:Main_page): "be sure to specify a User-Agent header that properly identifies your client. Don't use the default User-Agent provided by your client library".

the paragraph goes on about providing a means of contact; i'm not sure whether this relates to the author of the tool or the user. in any case, it might be a good idea to allow adding custom information to the string by environment variable or configuration option, so a user could operate a git-mediawiki client that identifies as "git-mediawiki/2.6.2 (http://wikis-as-apps.example.com/; operator@wikis-as-apps.example.com) MediaWiki::API/0.41".

**Comment by anarcat** [comment]
@tobbez i see that you have fixed #31 in 6a031f4. we have now merged the remote code on GitHub so you could send this as a pull request. would you mind sending us the fix as a PR? thanks!

**Comment by anarcat** [comment]
closed by #54 in e454e0c
