### ISSUE TITLE
[RFC] Move Git-Mediawiki's code out of git.git's contrib/ ?

### ISSUE THREAD

**Issue by moy** [Git-Mediawiki/Git-Mediawiki#34]
Git-Mediawiki is currently hosted in the `contrib/mw-to-git` directory of Git's source code. The reason it is this way is that I initially thought that the interaction with the Git community would lead to better code and a more lively project.

It seems I was wrong: I did not see much activity on Git's mailing-list other than mine on Git-Mediawiki, and the fact that patches have to be posted to Git's mailing-list and accepted according to Git's quality standard already discouraged several contributors.

I now think that Git-Mediawiki should be split into a project of its own. What do you think?

**Comment by lyubomyr-shaydariv** [comment]
I vote up.

1) At least, the issue tracker in this project is the only active way to interact with contributors.
2) Git contribution is too hardcore. I've tried to make one tiny contribution, but yep my tiny contribution was not accepted however it surprisingly has been accepted to the Gentoo repo.
3) git/git is closed for PRs
4) No more questions like what's the primary repo: this one or that one. This one, sure.

Probably something else...

**Comment by zarelit** [comment]
I totally agree with @lyubomyr-shaydariv

**Comment by greenrd** [comment]
I agree.

However a bigger problem is probably that it is written in Perl and not many people these days have cause to learn much Perl. In fact I never had cause to learn Perl even though I started programming 25 years ago...

**Comment by aurora** [comment]
I would be interested in participating in git-mediawiki, because it turns out to be a very valuable tool for me. But the way it's hosted in git/contrib discourages me. It just seems to be too "overcomplicated" to contribute in this way. So, i too would be very happy if this would be split into an own repository.

**Comment by MerlijnWajer** [comment]
I agree. It would be nice to see some of these patches merged.

**Comment by Yehonal** [comment]
Would be nice to have a mix of 2 things: A separated project where users can send their patches in a more familiar way. And then you can eventually send them to the git/contrib repository following git's rules.

(i'm having various issues even with submitGit app http://submitgit.herokuapp.com/ and my PR could not be accepted)

**Comment by jberkel** [comment]
Please move the code back (into this project). The only changes made inside the git main repository in the last years were spelling fixes. With all the changes to the mw api it requires ongoing maintenance. Managing these changes via github will be a lot simpler.

**Comment by anarcat** [comment]
it seems most people agree here - this should be separate. the next step would be to submit a patchset to the git mailing list to remove the code from there and restore it here.

**Comment by anarcat** [comment]
it seems that upstream git is open to the project moving back here, so I will look into doing that soon:

https://public-inbox.org/git/xmqqh8ug3xnq.fsf@gitster.mtv.corp.google.com/#t

then we can make a "code drop" from time to time into core git, presumably when we make releases here. or we just rip the code out of core...

any objections should be voiced in the next month, at which point I will feel entitled to make a release here. in any case, I'll start bringing back the history/repo here and we can work from there.

**Comment by moy** [comment]
The build system will probably need minor adjustments. IIRC we currently rely on Git's main Makefile to be in ../..

**Comment by anarcat** [comment]
So i did some `filter-branch` gymnastics to bring back the history from git-core into this repo, in 
9ffa017. But now the README is out of date... I wonder if that's a good occasion to tackle #9 at the same time and merge the wiki in here... Or at least use the wiki's frontpage as a README?

**Comment by anarcat** [comment]
Furthermore, some changes I sent to the mailing list are, ironically, pending merge there, so it may be better to way for that dust to settle down before completing the merge. The merge procedure is in the commitlog of 9ffa017.

**Comment by moy** [comment]
Should be OK now, the pending patches have been merged in git.git's master.

I don't think you need to *merge* the git.git history into Git-Mediawiki: you can just replace whatever is in Git-Mediawiki by what's in git.git (you may keep a backup of master in a separate branch, just in case). Old commits in Git-Mediawiki correspond to drafts done before integration in git.git's contrib, and more recent commits are just the trivial `README.md` file. If you just replace the current history with git.git's, you don't have an outdated README anymore, and you can deal with #9 independently.

**Comment by anarcat** [comment]
hmm... well merging the tree here is not the hard part. the hard part is tearing it out of git.git, with history. now we could just drop the latest subdirectory in here and commit it as such, but i made a procedure that can reliably import the history, so why not use that?

and yes, I think #9 can be done separately as well.

**Comment by moy** [comment]
Yes, merging is not the hard part, but it's what gives you an outdated README.md in your [comment above](https://github.com/Git-Mediawiki/Git-Mediawiki/issues/34#issuecomment-341579620). I'm all for importing the history, just mentioning that a simple force-push is probably better than `merge --allow-unrelated-histories`.

**Comment by anarcat** [comment]
oh. well my thinking was that i would `merge` then edit the `README` as needed and fix the merge. :)

**Comment by anarcat** [comment]
i mean the whole problem with the readme would happen with a force-push as well: there's no README in the git.git contrib module either...

**Comment by moy** [comment]
> there's no README in the git.git contrib module either...

Yes. What I meant is that you'd just get rid of the current README.md so you wouldn't get an inconsistent state with the code and a REAMDE saying the code isn't here in the same commit. For sure, this leaves room for another, better README.md.

**Comment by anarcat** [comment]
okay, so what you're saying is if the merge commit also removes the README file, it's okay to proceed the way i suggested?

**Comment by moy** [comment]
What I'm saying is there's no need for a merge commit. Just discard the current history.

I've created a "old-history" branch containing the same as master, so you can thow away whatever is in master. Just `filter-branch` the git.git history and force-push it to Git-Mediawiki's master.

**Comment by anarcat** [comment]
On 2017-11-18 16:00:32, Matthieu Moy wrote:
> What I'm saying is there's no need for a merge commit. Just discard the current history.
>
> I've created a "old-history" branch containing the same as master, so you can thow away whatever is in master. Just `filter-branch` the git.git history and force-push it to Git-Mediawiki's master.

meh. i don't see what this brings us.

a merge is easy to do and keeps the old history correctly as well, which
may eventually be useful. why discard it?

**Comment by moy** [comment]
As you want, but the old history is 1) a trivial and obsolete README.md file, and 2) drafts written before cleaning up the history and submitting to git.git. IOW, it's the history before proper `rebase -i`, not the one you want to keep forever, and certainly not the one you want to pop up when you `git bisect` or `git blame`.

*The* history is the one in git.git, that's the one you want to keep.

**Comment by anarcat** [comment]
On 2017-11-18 16:24:30, Matthieu Moy wrote:
> As you want, but the old history is 1) a trivial and obsolete README.md file, and 2) drafts written before cleaning up the history and submitting to git.git. IOW, it's the history before proper `rebase -i`, not the one you want to keep forever, and certainly not the one you want to pop up when you `git bisect` or `git blame`.

That's the thing: the history in this repo is not only the README file,
there's actual code hidden behind. That code was removed when migrated
to git.git, but i still think it's historically significant and *may*
show up in blame/bisect.

Now, you wrote that code, so I may be completely mistaken, but it is not
harder for me to keep that history, and I don't see the point of
destroying it, so I'll just go ahead and merge this, discarding the
README file, obviously, if you don't mind. :)

**Comment by anarcat** [comment]
So I finally made pull request #46 to bring back the code the way I think is right. Let me know if you want anything changed!

**Comment by anarcat** [comment]
just so we don't stall again here, i'll merge #46 tomorrow if there's no objection.

**Comment by anarcat** [comment]
that is now done.
