### ISSUE TITLE
Could you please add ignore edit conflicts option?

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [Git-Mediawiki/Git-Mediawiki#35]
Could you please add ignore edit conflicts option once you probably get the source code back to this repo? Commenting out the `basetimestamp` parameter in the script directly really helps a lot while restoring my died wiki. It seems to be very and very easy for a Perl guy, but I'm that one, so I can't make it nice.

This is easy (declare/parse the option):

``` patch
+# Ignore edit conflicts
+my $ignore_edit_conflicts = run_git("config --get --bool remote.${remotename}.ignoreEditConflicts");
+chomp($ignore_edit_conflicts);
+$ignore_edit_conflicts = ($ignore_edit_conflicts eq 'true');
+
```

But it's not that easy to me: is it possible to "block" the following line if `$ignore_edit_conflicts` is `true` (the `$mediawiki->edit` invocation block)?

``` perl
basetimestamp => $basetimestamps{$oldrevid},
```

The most similar thing I've found is http://stackoverflow.com/a/10415472/166589 but it seems to work with arrays of that structure. Would it be possible to make it a oneliner?

Thank you!

**Comment by anarcat** [comment]
could you provide an actual patch here?

it seems to me this could be just a documentation issue - users could just configure their repository with that option, no?

what's the use case here? why would we allow conflicts to be committed, and how could they possibly happen?

thanks!

**Comment by lyubomyr-shaydariv** [comment]
@anarcat A good question. I had my wiki lost its database without having a backup two years ago, and since I had an older wiki backup generated by git and this remote helper I was able to reconstruct the wiki literally step by step. I had many issues that time and now I cannot really recall its use case unfortunately. Maybe it was something about the age of fetched and pushed contents, and maybe I had a very specific case with just the locally patched helper. Close?

**Comment by anarcat** [comment]
yeah, without a way to reproduce, and given this was quite an exotic situation that we would *expect* a conflict (and that there's a user-accessible workaround), I would say we can close this...

reopen if you disagree, of course! :)
