### ISSUE TITLE
Limit the perl dependency

### ISSUE THREAD

**Issue by alphaonex86** [Git-Mediawiki/Git-Mediawiki#39]
Hello,

When I install git with the useflag mediawiki in need perl under gentoo, it have too many deps:
[ebuild  N     ] virtual/perl-Carp-1.360.0-r1::gentoo  0 KiB                                                                                                                                  
[ebuild  N     ] dev-perl/LWP-MediaTypes-6.20.0-r1::gentoo  0 KiB                                                                                                                             
[ebuild  N     ] virtual/perl-XSLoader-0.200.100_rc::gentoo  0 KiB                                                                                                                            
[ebuild  N     ] virtual/perl-Compress-Raw-Zlib-2.68.0-r1::gentoo  0 KiB
[ebuild  N     ] dev-perl/Encode-Locale-1.30.0-r1::gentoo  0 KiB
[ebuild  N     ] dev-perl/HTML-Tagset-3.200.0-r1::gentoo  0 KiB
[ebuild  N     ] virtual/perl-JSON-PP-2.273.0.100_rc-r1::gentoo  0 KiB
[ebuild  N     ] virtual/perl-libnet-3.50.100_rc::gentoo  0 KiB
[ebuild  N     ] virtual/perl-IO-1.350.100_rc::gentoo  0 KiB
[ebuild  N     ] virtual/perl-Time-Local-1.230.0-r5::gentoo  0 KiB
[ebuild  N     ] virtual/perl-Digest-MD5-2.540.0-r2::gentoo  0 KiB
[ebuild  N     ] virtual/perl-CPAN-Meta-YAML-0.12.0-r3::gentoo  0 KiB
[ebuild  N     ] virtual/perl-Parse-CPAN-Meta-1.441.400.100_rc::gentoo  0 KiB
[ebuild  N     ] virtual/perl-IPC-Cmd-0.920.100_rc-r1::gentoo  0 KiB
[ebuild  N     ] virtual/perl-File-Path-2.90.0-r5::gentoo  0 KiB
[ebuild  N     ] dev-perl/Sub-Name-0.50.0-r1::gentoo  4 KiB
[ebuild  N     ] perl-core/Encode-2.730.0::gentoo  0 KiB
[ebuild  N     ] virtual/perl-Compress-Raw-Bzip2-2.68.0-r1::gentoo  0 KiB
[ebuild  N     ] virtual/perl-Text-ParseWords-3.300.0-r2::gentoo  0 KiB
[ebuild  N     ] virtual/perl-Perl-OSType-1.8.0-r1::gentoo  0 KiB
[ebuild  N     ] virtual/perl-Module-Metadata-1.0.26-r1::gentoo  0 KiB
[ebuild  N     ] virtual/perl-ExtUtils-ParseXS-3.280.0-r1::gentoo  0 KiB
[ebuild  N     ] virtual/perl-ExtUtils-Manifest-1.700.0-r3::gentoo  0 KiB
[ebuild  N     ] virtual/perl-ExtUtils-Install-2.40.0-r2::gentoo  0 KiB
[ebuild  N     ] virtual/perl-ExtUtils-CBuilder-0.280.221-r1::gentoo  0 KiB
[ebuild  N     ] virtual/perl-version-0.990.900-r4::gentoo  0 KiB
[ebuild  N     ] virtual/perl-Digest-SHA-5.950.100_rc-r1::gentoo  0 KiB
[ebuild  N     ] dev-perl/HTTP-Date-6.20.0-r1::gentoo  0 KiB
[ebuild  N     ] dev-perl/Try-Tiny-0.240.0::gentoo  USE="-minimal {-test}" 30 KiB
[ebuild  N     ] virtual/perl-Encode-2.730.0-r1::gentoo  0 KiB
[ebuild  N     ] dev-perl/HTML-Parser-3.710.0-r1::gentoo  USE="{-test}" 0 KiB
[ebuild  N     ] virtual/perl-IO-Compress-2.68.1_rc::gentoo  0 KiB
[ebuild  N     ] dev-perl/Digest-HMAC-1.30.0-r1::gentoo  8 KiB
[ebuild  N     ] dev-perl/Net-SSLeay-1.800.0::gentoo  USE="-examples (-libressl) -minimal {-test}" 387 KiB
[ebuild  N     ] dev-perl/Class-Singleton-1.500.0::gentoo  8 KiB
[ebuild  N     ] dev-perl/Exporter-Tiny-0.42.0::gentoo  USE="{-test}" 32 KiB
[ebuild  N     ] virtual/perl-CPAN-Meta-2.150.1-r1::gentoo  0 KiB
[ebuild  N     ] dev-perl/Module-Build-0.421.600::gentoo  USE="{-test}" 0 KiB
[ebuild  N     ] dev-perl/IO-Socket-SSL-2.24.0::gentoo  USE="-idn" 0 KiB
[ebuild  N     ] dev-perl/List-MoreUtils-0.413.0::gentoo  USE="{-test}" 129 KiB
[ebuild  N     ] dev-perl/Authen-SASL-2.160.0-r1::gentoo  USE="-kerberos" 45 KiB
[ebuild  N     ] dev-perl/File-Listing-6.40.0-r1::gentoo  0 KiB
[ebuild  N     ] dev-perl/WWW-RobotRules-6.20.0::gentoo  0 KiB
[ebuild  N     ] dev-perl/IO-HTML-1.1.0::gentoo  USE="{-test}" 0 KiB
[ebuild  N     ] dev-perl/HTTP-Message-6.110.0::gentoo  USE="{-test}" 0 KiB
[ebuild  N     ] dev-perl/Module-Runtime-0.14.0::gentoo  USE="{-test}" 17 KiB
[ebuild  N     ] dev-perl/Net-HTTP-6.90.0::gentoo  USE="-minimal" 0 KiB
[ebuild  N     ] dev-perl/HTML-Tree-5.30.0-r1::gentoo  USE="{-test}" 145 KiB
[ebuild  N     ] dev-perl/Net-SMTP-SSL-1.30.0::gentoo  USE="{-test}" 3 KiB
[ebuild  N     ] dev-perl/Error-0.170.240::gentoo  USE="{-test}" 31 KiB
[ebuild  N     ] dev-perl/List-AllUtils-0.90.0::gentoo  USE="{-test}" 19 KiB
[ebuild  N     ] dev-perl/Class-Factory-Util-1.700.0-r1::gentoo  12 KiB
[ebuild  N     ] dev-perl/HTTP-Negotiate-6.10.0::gentoo  0 KiB
[ebuild  N     ] dev-perl/HTTP-Daemon-6.10.0-r1::gentoo  0 KiB
[ebuild  N     ] dev-perl/HTTP-Cookies-6.10.0::gentoo  0 KiB
[ebuild  N     ] dev-perl/Module-Implementation-0.90.0::gentoo  USE="{-test}" 19 KiB
[ebuild  N     ] dev-perl/Dist-CheckConflicts-0.110.0::gentoo  USE="{-test}" 20 KiB
[ebuild  N     ] dev-perl/Params-Validate-1.220.0::gentoo  USE="{-test}" 123 KiB
[ebuild  N     ] dev-perl/DateTime-Locale-0.460.0::gentoo  USE="{-test}" 2497 KiB
[ebuild  N     ] dev-perl/DateTime-TimeZone-1.930.0::gentoo  USE="{-test}" 871 KiB
[ebuild  N     ] dev-perl/DateTime-1.200.0::gentoo  USE="{-test}" 216 KiB
[ebuild  N     ] dev-perl/DateTime-Format-Strptime-1.560.0::gentoo  USE="{-test}" 36 KiB
[ebuild  N     ] dev-perl/DateTime-Format-Builder-0.810.0-r1::gentoo  39 KiB
[ebuild  N     ] dev-perl/DateTime-Format-ISO8601-0.80.0-r1::gentoo  USE="{-test}" 21 KiB
[ebuild  N     ] dev-perl/libwww-perl-6.150.0::gentoo  USE="ssl" 0 KiB
[ebuild  N     ] dev-perl/LWP-Protocol-https-6.60.0::gentoo  0 KiB
[ebuild  N     ] dev-perl/MediaWiki-API-0.410.0::gentoo  USE="{-test}" 33 KiB

Cheers,

**Comment by moy** [comment]
Most of these dependencies seem to come from HTTP support, and we clearly can't get rid of this.

AFAICT, we depend on:

* MediaWiki::API
* DateTime::Format::ISO8601

We clearly don't want to get rid of the first. It would be possible to get rid of the second, but someone  would need to implement a date parser, and I don't really see the point in reimplementing it if it already exists somewhere (we're talking about a few MB of bandwidth and disk space here ...).

**Comment by alphaonex86** [comment]
Then where is the MediaWiki::API project page please?

**Comment by moy** [comment]
I don't have more information than you, but you can find info here:
http://search.cpan.org/~exobuzz/MediaWiki-API-0.41/lib/MediaWiki/API.pm#BUGS

I'm closing the bug because I don't think there's much to do here. Feel free to reopen if you have more arguments.
