### ISSUE TITLE
filenames can be too long

### ISSUE THREAD

**Issue by anarcat** [Git-Mediawiki/Git-Mediawiki#45]
on a wiki i'm replicating, i have found this error:

```
$ LANG=C git co master
error: cannot stat 'Talk:Oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh_no_oh.mw': File name too long
```

Obviously, that's a horrible page name, but we should gracefully handle this...

**Comment by anarcat** [comment]
patch posted on the mailing list: https://public-inbox.org/git/20171029163714.4818-1-anarcat@debian.org/

**Comment by moy** [comment]
Patch merged to master, let's close this.
