### ISSUE TITLE
git clone creates duplicate history

### ISSUE THREAD

**Issue by eldering** [Git-Mediawiki/Git-Mediawiki#68]
## Environment

 * Operating system: Debian GNU/Linux 10.1 (Buster)
 * Git version: 2.20.1
 * Mediawiki remote version: unsure
 * Install method: Debian package git-mediawiki=1:2.20.1-2 (default from Buster)
 * Site URL: https://clics.ecs.baylor.edu/
 * Mediawiki site version: 1.33.1
 * Git configuration: https://pastebin.com/5gQumZar

When I try to clone a single page (haven't tried a full wiki), I end up with a git history that contains the mediawiki history of that page, and then the exact same history appended again as new git commits. The list of git notes is not duplicate.

I've also tried first initializing an empty git repository and then run git pull, which does work fine.

**Comment by RubenKelevra** [comment]
@eldering is e41ee9b3a32416df381cdc79f63350665c84151e fixing this for you?

**Comment by eldering** [comment]
The original mediawiki site is not available anymore, so I can't easily test this. I guess the issue can be closed assuming it fixed things.
