### ISSUE TITLE
You appear to have cloned an empty MediaWiki.

### ISSUE THREAD

**Issue by adrelanos** [Git-Mediawiki/Git-Mediawiki#70]
* It's a public wiki. No password protection for viewing.
* https://www.whonix.org/wiki
* Operating system: Debian buster
* Git version: git version `2.26.1`
* Mediawiki remote version: `1.34.1`
* Install method: https://packages.debian.org/buster-backports/git-mediawiki
* Site URL: https://www.whonix.org/wiki/
* Mediawiki `1.34.1`
* Git configuration:

```
 git config -l
```
```
user.name=whonix
user.email=postmaster at whonix.org (manually redacted to reduce spam)
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
```

```
git clone mediawiki::https://www.whonix.org/w
```

Says `Found 0 revision(s).` for all pages.

> [snip]
> page 799/800: Upgrade
>   Found 0 revision(s).
> page 800/800: Dev/Archived Discussions
>   Found 0 revision(s).
> You appear to have cloned an empty MediaWiki.
> fatal: could not read ref refs/mediawiki/origin/master

Any advice?

**Comment by cooljeanius** [comment]
huh I wonder if this was the same issue I was running into a few years back...

**Comment by adrelanos** [comment]
Could you please send a pull request here?

https://github.com/git/git/blob/master/contrib/mw-to-git/git-remote-mediawiki.perl
