### ISSUE TITLE
Only 500 revisions of a page are pulled

### ISSUE THREAD

**Issue by hexmode** [Git-Mediawiki/Git-Mediawiki#73]
Using the `by_page` strategy to clone [Barack_Obama](https://en.wikipedia.org/wiki/Barack_Obama) from wikipedia, only the first 500 revisions of the page are pulled.  Example output:

```
$ git clone -c remote.origin.pages=Barack_Obama \
            mediawiki::https://en.wikipedia.org/w
....
496/500: Revision #13281747 of Barack_Obama
497/500: Revision #13365658 of Barack_Obama
498/500: Revision #13382402 of Barack_Obama
499/500: Revision #13382456 of Barack_Obama
500/500: Revision #13382631 of Barack_Obama
$ cd w
$ git lg
* d7c3c0f - (HEAD -> master, origin/master, origin/HEAD, refs/mediawiki/origin/master) *Empty MediaWiki Message* (17 years ago) <152.163.100.200>
* b4e77cb - *Empty MediaWiki Message* (17 years ago) <152.163.100.200>
* 2c3b9e0 - /* Keynote address */ Shamus to Seamus (17 years ago) <Thomasngo>
* 5d95ba4 - Reverted edits by [[Special:Contributions/205.188.117.70|205.188.117.70]] to last version by Radicalsubversiv (17 years ago) <Meelar>
* df9a05b - /* Early life */ (17 years ago) <205.188.117.70>
* 50ee812 - rv vandalism (17 years ago) <Radicalsubversiv>
* 65abd49 - *Empty MediaWiki Message* (17 years ago) <Mochaliz>
* 5e3bda9 - rv vandal. (17 years ago) <Harro5>
* 111800d - *Empty MediaWiki Message* (17 years ago) <130.212.120.6>
* 43374e6 - Robot: Removing from category The Greatest American (17 years ago) <CanisRufus>
```

(I was initially worried that the dates might be wrong, but [it looks like they are correct](https://en.wikipedia.org/w/index.php?title=Barack_Obama&dir=prev&limit=500&action=history).)

**Comment by moy** [comment]
git-remote-mediawiki normally fetches revisions 500 by 500, to avoid doing too much in a single request. It seems you're only getting the first batch :-(.

**Comment by hexmode** [comment]
I'm familiar with the MW API and the limits on it (e.g. there is a limit of 500 for queries), but I was expecting to have it use the continuation parameter and ask for more.

I thought it did this, but I've coded the continuation before, so this isn't really a problem.  I'm just recording the issues that need to be addressed.
